version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: db_service
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./configs/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  ingestion:
    build:
      context: .
      dockerfile: src/ingestion/Dockerfile
    container_name: ingestion_pipeline
    depends_on:
      - db
    env_file:
      - ./configs/.env
    volumes:
      - .:/app
    working_dir: /app/src/ingestion

  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    container_name: api_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./configs/.env
    volumes:
      - .:/app
    working_dir: /app/src/api

  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    container_name: streamlit_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - db
      - api
    volumes:
      - .:/app
    working_dir: /app/streamlit

  # Nuevo servicio para Spark/Sedona
  spark:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: spark-sedona
    hostname: spark
    ports:
      - "4040:4040"  # UI Spark
      - "7077:7077"  # Spark Master
      - "8080:8080"  # Spark Web UI
      - "8888:8888"  # Jupyter Notebook
    volumes:
      - ./notebooks:/notebooks
      - ./data:/data
      - .:/app
    environment:
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=8g
    command: ["/entrypoint.sh"]

  # Airflow Webserver
  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-webserver
    depends_on:
      - db
      - spark
    ports:
      - "8081:8080"  # Puerto 8081 para evitar conflicto con Spark UI
    env_file:
      - ./configs/.env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://geo_user:NekoSakamoto448@db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=bike_sharing_secret_key
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - .:/app
    command: webserver

  # Airflow Scheduler
  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
    env_file:
      - ./configs/.env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://geo_user:NekoSakamoto448@db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - .:/app
    command: scheduler

volumes:
  pgdata: